### ISSUE TITLE
Adventure Support?

### ISSUE THREAD

**Issue by schmupai** [RyseInventory/RyseInventory#52]
Hello,
I just wanted to ask if you plan on adding Adventure Support?
https://docs.adventure.kyori.net/getting-started.html

(I know that its possible to use the text serializer to convert it to a normal string but would be nice to be able to directly use components)

Thank you!

**Comment by Rysefoxx** [comment]
Hello,

of course this is planned. Since I use Adventure myself. Unfortunately, I have not yet come to this. When exactly I can not say unfortunately.

**Comment by schmupai** [comment]
Glad to hear. Thank you very much for your answer!

**Comment by Rysefoxx** [comment]
Adventure Support is now available in v1.5.7.
