### ISSUE TITLE
Failed to open RyseInventory in v1.5.7

### ISSUE THREAD

**Issue by RenGV** [RyseInventory/RyseInventory#61]
**Describe the bug**
When opening the inventory I get an error because I don't have the Adventure dependency. Is it a requirement to add that dependency in this version?

**Code (Optional)**
https://pastebin.com/LketcuAE

**Comment by Rysefoxx** [comment]
Yes. Even if you pass a string in the title, for example, it will be made into a component. I will eventually add in that you don't have to manually add adventure.

Currently you have to have the dependency in your runtime.

**Comment by Rysefoxx** [comment]
Should be fixed in version v1.6.0.
https://github.com/RyseInventory/RyseInventory/releases/tag/v1.6.0
