### ISSUE TITLE
Possibility for parent inventory?

### ISSUE THREAD

**Issue by ch4ika** [RyseInventory/RyseInventory#65]
There is the possibility to get the last opened inventory, but is there also the possibility to create a parent inventory like with the SmartInv? Or should one put that over the property?

1.
`inventoryManager.getLastInventory(null).ifPresent(inventory -> {});`

2.
`contents.setProperty("parent", ryseInventory);`

**Comment by Rysefoxx** [comment]
1) Why do you pass null? This will lead to errors.

2) No, the possibility does not currently exist.

**Comment by ch4ika** [comment]
The first was just an example.

Your 2nd answer answered the question.
