### ISSUE TITLE
Misspelled 'bottom' in CornerType.

### ISSUE THREAD

**Issue by ch4ika** [RyseInventory/RyseInventory#69]
`https://github.com/RyseInventory/RyseInventory/blob/master/plugin/src/main/java/io/github/rysefoxx/inventory/plugin/other/CornerType.java`

```
public enum CornerType {

    TOP_LEFT,
    TOP_RIGHT,
    BOTTM_LEFT,
    BOTTOM_RIGHT,

}
```

> BOTTM_LEFT

**Comment by Rysefoxx** [comment]
Fixed. Thanks :)
