### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ch4ika** [RyseInventory/RyseInventory#71]
I noticed that both caches are not freed from memory when quiting, so they stay in the cache all the time.
   
   InventoryManager:
    `private final HashMap<UUID, List<CustomInventory>> lastInventories = new HashMap<>();`
  `private final HashMap<UUID, Long> lastOpen = new HashMap<>();`

**Comment by Rysefoxx** [comment]
Fixed in next update. Thank you

**Comment by ch4ika** [comment]
The complete map is now cleared and not by the player himself.
